### PR TITLE
Allow higher version of deps in setup.py

### PR DESCRIPTION
**Pull request by rmuslimov**
Thanks for your work.

### CODE REVIEW

**Comment by Yloganathan** [comment]
@semirook I am having an issue where having flask 1.0 and snaql fails the dependency resolution for jinja2. 
```Could not find a version that matches jinja2==2.9.5,>=2.10```
This PR helps address this issue. Any news on when this will get merged?

Thank you!

**Comment by semirook** [comment]
Sure, thank you.

**Comment by jjmurre** [comment]
@semirook Is it possible to publish the version with this PR to PyPI? 
Tx.

**Comment by zaiev** [comment]
NP. It's there already. Use 0.4.2

**Comment by jjmurre** [comment]
Great!

**Pull request merged**
